---
before:
  hooks:
    - make init

archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  wrap_in_directory: clickhouse_exporter

  format: zip
  files:
    - LICENSE
    - README.md
