---

env:
  global:
    - secure: "HzzfC14h4avZlndMqJZGt80uU+JoXepHQHMk8YSsadWUZo4J8T6Xi9fOEK2rlNf43rByQJJugawQrwEPKOkAn8OcD1iOzALr4rLZNnKifKrffEXHEQ7zm8VuhyGfwiiP0Jxsx5Oyt9jVJV8Z/exxLy7XY1u4nGs2LLnsxtcoCmB8QOXzvqk4ZmDOr/KwsuOh5Pv5aPQOUOTeI7MksN1esMDykHnZ3/8r6De+nkNE1gli/dOFMG3skc6ywKj6BaDGiMO38Y6u8qkhSx0yolaRjlI/3sthhED/7f0RujYyQb3JKqz5MitvSRoYf+cIu9j0zxQRHejphJYD+RQIMgnU/YU+mlsqbd1s1ZBsAIt/pUtmILrkyRjDRdboKO6N0LTiIo8rT5V6tkcxOyx53GViBF+d818ry1nq+e+Pzbmhb1d/zT2ghAUUzyPR2QlTB/2bAh3j1eSzzcZIw5jc/emkbibgL6V5fnaQITKwl2ns4DyrccSyBNSh0JeA0RSsp1dtOh2/eh6kzf2Bxer9qnAT4vXFJDu9wHGxnOzDmQctOsAP4mf7IiIMtSNToD1HtAeMVE3gF/AqEmdHpXEjbXq7XxAEroKJ+893JVey4MYyKBlV3UsW38Ey0/0tKkLo6h1mEiNdy2GlUjdwP5JK3jgotTSVVwvJSIHSd015HhxQaNg="
dist: xenial
sudo: required
language: go

go:
  - 1.11.6
  - 1.12.1

go_import_path: github.com/f1yegor/clickhouse_exporter

services:
  - docker

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose up -d

  - make init

script:
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
  - zip clickhouse_exporter-$TRAVIS_TAG.zip /go/bin/clickhouse_exporter
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = 'linux' && $TRAVIS_GO_VERSION = '1.12.1'
